################################################################################
#######################Application specific#####################################
################################################################################

URL=https://rocket.new
gmail=


spreadsheetId=1T9D_Hwfh4qFOOzdyt-l4N3PC2bwVZKf3Qu20EW9S9jk
range =A2:D

################################################################################
googleSheetUrl=
################################################################################
#########################Global configurations##################################
################################################################################
#do not move logs, reports & stop drivers if parallel execution
parallelExecution=false

#to kill the driver executables for abrupt stopping when true
debugging=true

# cyfer related
passwordEncrypted=true
key=qcautomation@mem

#your path must contain '/' in them and there must be no spaces in between
#reportName - optional
reportPath=./Generated/Report/
reportName=
#OPTIONAL -To skip screenshots for pass & info result statements ignoring project given parameter to reduce the report size
skipPassInfoScreenshot=false
#OPTIONAL - report screenshot image scaling to decide compression
reportScreenshotScale=1
#OPTIONAL - report screenshot image quality to decide compression
reportScreenshotQuality=

#logs file path & logs file starting name is optional or can be empty
#your path should start with "./" or with drive beginnin
#your path must contain '/' or '\\' in them and there must be no spaces in between
#logs allowed values - true, false
logsFilePath=./Generated/logs
logsFileStartingName=
logs=true

#getFirefoxLogs=true - Not supporting for all browser so replaced with 'getBrowserDriverLogs'

#move to next test once a single step fail has been logged for current test
onFailNextTest=false

#re run the failed scenario - optional
reRunCount=0

#browser allowed values - firefox, chrome, edge, FIREFOX, CHROME, EDGE
#NON_GUI mode may not work with Javascript heavy webapps i.e. AngularJS apps
browser=chrome
#for non gui in firefox & chrome | values allowed true or false
headless=false
#OPTIONAL - to get the browser driver logs for analysis 
getBrowserDriverLogs=false

#driver file path depending on the browser given
#driver=./libs/drivers/chromedriver.exe

#waitInSeconds is a global wait in seconds, change in positive number
#implicit wait is same as below 
#explicit wait will be x10 of below value at start
waitInSeconds=3

#once sikuli is installed then use sikuli based on below parameter. allowed values - true, false
sikuli=false
#Sikuli operations timeout
sikuliTimeout=30

#deleteCookies allowed values - true, false
deleteCookies=false

#download folder working for firefox and chrome - it's mandatory
#It's should be of rmeote shared folder in case of grid execution
downloadFolder=./Generated/Download
#manage if files should get auto download or not
autoDownload=true

#Chrome or firefox user profile for the cookies -OPTIONAL
userProfilePath=

#optional pages java files path - containing '\\' or '/' in path
#Leave it blank for default path | default path is .\\pages
pagesPath =

#browser session accepting unsecure certs(add value false below) or should check for certs(add value true below)
checkSSLCertificates=true

################################################################################

################################################################################
#################### Report Portal Configuration ###############################
################################################################################

#report portal end point/server to upload the report zip file
#optional leave it blank if Report Portal feature not needed
reportPortalURL=
#report portal server side folder to show report in the url in given hierarchy 
#should end with '/' as will be appending client code
reportPortalFolder=Framework\\TemplateProject\\v20240926
#optional - Based on QuickCap - can be utilize as general as well
clientCode=MEM
#optional - Based on QuickCap - can be utilize as general as well
userType=NORMAL

################################################################################

################################################################################
#################### Auto Email Configuration ##################################
################################################################################

#Email will be send based on below user input if the report is
#uploaded to server 
sendEmail=false
#To send email if execution has a fail test; allowed values - true or false
sendEmailOnFailOnly=false
host=smtp.gmail.com
emailusername=patelmihir9111@gmail.com
emailpassword=
#separate with ',' for multiple recepients
toemail=patelmihir9111@gmail.com
#if available email will be decrypted else will be used plain

################################################################################
#################### Report Upload Configuration ###############################
################################################################################
accessTokenFilePath=./libs/access_token.txt
#API to generate token
axesTokenGenerateAPI=
#https://axes.meditab.in/auth/generate-token
#token user credentials for api
tokenUserName=apiuser
tokenPassword=FEq3zbEI8qGb6y5sCRJRBw==
#ssl certificate path
certificatesTrustStorePath=./libs/jssecacerts

################################################################################