package suites.appsuites;

import java.util.List;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.api.services.sheets.v4.Sheets;
import com.google.api.services.sheets.v4.model.ValueRange;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.LoadState;

import framework.input.Configuration;
import framework.reporter.ScreenshotType;
import pages.SubModule;
import pages.data.AiValidationResponse;
import pages.data.GeneratedAppSummary;
import suites.appsuites.utils.GSheetOperation;
import suites.basesuites.RocketBaseSuite;

/**
 * Project specific base suite to be extended by every suite
 */
public class CreateAppSuite extends RocketBaseSuite implements SubModule {

	@Test(priority = 0, enabled = true, dataProvider = "customInput", description = "(Rocket Process Automation) <br>"
			+ "1. Launch the rocket.new url >> Url should be launch. <br>"
			+ "2. Click on sign in button >> Sign popup should be open. <br>"
			+ "3. Enter Gmail Id and click on continue button >> Otp field should be display. <br>"
			+ "4. Enter otp and click on continue button >> Login should be successfully and home button should be display. <br>"
			+ "5. Click on new task and enter prompt which is generated by AI Tool >> Prompt should be enter <br>"
			+ "6. Click on send button >> The development of the application should begin. <br>"
			+ "7. Click on launch button >> Successfully click on launch button and URL should be display.<br>"
			+ "8. Take the Url and Prompt >> Enter both the things in google sheet. <br>"
			+ "9. Launch the new generated url >> It should be successfully launch.")
	public void generateApp(String numberOfApps, String useCase, String technology, String typeOfApplication,
			String rowNumber) {

		String url = "Not Generated";

		// generating prompt from GEMINI
		String response = geminiService.generateGeminiPrompt(numberOfApps, useCase, technology, typeOfApplication);

		// if response is not empty then move ahead
		if (!response.isBlank()) {

			// select application type from that
			if (home.selectApplicationType(useCase, typeOfApplication)) {

				url = home.enterPromptAndGenerateURL(response);

			}
		}

		// update the google sheet
		gSheetOperation.updateCell(response, url, Integer.valueOf(rowNumber));

		if (!url.equalsIgnoreCase("Not Generated")) {

			GeneratedAppSummary summary = exploreWebsite(url);

			// generating summary of new application from GEMINI
			String generatedSummaryReport = geminiService
					.generateSummary(response, summary.buttons, summary.links, summary.bodyText).replace("```json", "")
					.replace("```", "").trim();

			ObjectMapper mapper = new ObjectMapper();

			try {

				AiValidationResponse aiResponse = mapper.readValue(generatedSummaryReport, AiValidationResponse.class);

				RESULT.INFO("Requirement Match Score: " + aiResponse.score, false, ScreenshotType.browser);

				RESULT.INFO("Working Feature: " + aiResponse.working_features, false, ScreenshotType.browser);

				RESULT.INFO("Missing Feature: " + aiResponse.missing_features, false, ScreenshotType.browser);

				RESULT.INFO("Broken Feature: " + aiResponse.broken_features, false, ScreenshotType.browser);

				RESULT.INFO("AI Summary: " + aiResponse.summary, false, ScreenshotType.browser);

			} catch (JsonProcessingException e) {
				RESULT.ERROR("An error occurred while converting the response into JSON", e, true,
						ScreenshotType.browser);
			}

		} else {
			RESULT.FAIL("Failed to generated New Application from Rocket.new", false, ScreenshotType.browser);
		}

	}

	@DataProvider(name = "customInput")
	public Object[][] customInput() {

		try {

			gSheetOperation = new GSheetOperation();

			Sheets sheetsService = gSheetOperation.getSheetService();

			String sheetName = CreateAppSuite.class.getSimpleName();
			String cellRange = Configuration.getConfigProp("range");

			String range = sheetName + "!" + cellRange;

			log.info("Reading data from range: " + range);

			ValueRange response = sheetsService.spreadsheets().values().get(spreadSheetId, range).execute();

			List<List<Object>> values = response.getValues();

			if (values == null || values.isEmpty()) {

				log.error("No data found in Google Sheet.");

				return new Object[0][0];
			}

			int rowCount = values.size();
			int columnCount = values.get(0).size();

			data = new Object[rowCount][columnCount + 1];

			for (int i = 0; i < rowCount; i++) {

				List<Object> row = values.get(i);

				for (int j = 0; j < columnCount; j++) {

					if (j < row.size()) {

						data[i][j] = String.valueOf(row.get(j));

					} else {

						data[i][j] = "";
					}
				}

				// Add Google Sheet row number
				data[i][columnCount] = String.valueOf(i + 2);
			}

			log.info("Successfully fetched data from Google Sheet.");

		} catch (Exception e) {

			log.error("Error while reading Google Sheet data.", e);
			RESULT.FAIL("Failed to get Input data from the google sheet", false, ScreenshotType.browser);
		}

		return data;
	}

	/**
	 * Explore the newly launch website in playwright
	 * 
	 * @param url
	 *            to navigate
	 * @return object of app's summary
	 */
	private GeneratedAppSummary exploreWebsite(String url) {

		GeneratedAppSummary summary = new GeneratedAppSummary();

		try (Playwright playwright = Playwright.create()) {

			Browser browser = playwright.chromium()
					.launch(new BrowserType.LaunchOptions().setHeadless(false).setArgs(List.of("--start-maximized")));

			BrowserContext context = browser.newContext(new Browser.NewContextOptions().setViewportSize(null));

			// Navigate to url
			Page page = context.newPage();
			page.navigate(url);
			RESULT.PASS("Launching URL: " + url, true, ScreenshotType.fullScreen);

			// WAIT
			page.waitForLoadState(LoadState.DOMCONTENTLOADED);
			page.waitForTimeout(8000);

			// PAGE TITLE
			String title = page.title();
			RESULT.PASS("PAGE TITLE: " + title, false, ScreenshotType.browser);

			// BUTTONS
			List<String> buttons = page.locator("button").allTextContents();
			for (String button : buttons) {
				if (!button.isBlank()) {
					summary.buttons.add(button);
					summary.clickableElements.add(button);
				}
			}
			RESULT.INFO("Buttons: " + buttons, true, ScreenshotType.browser);

			// LINKS
			List<String> links = page.locator("a").allTextContents();
			for (String link : links) {

				if (!link.isBlank()) {
					summary.links.add(link);
					summary.clickableElements.add(link);
				}
			}
			RESULT.INFO("Links: " + links, false, ScreenshotType.browser);

			// INPUTS
			int inputCount = page.locator("input").count();
			RESULT.INFO("Inputs: " + inputCount, false, ScreenshotType.browser);

			// PAGE TEXT
			String bodyText = page.locator("body").innerText();
			summary.bodyText = bodyText;

			browser.close();
		}

		return summary;
	}
}
