package suites.appsuites;

import java.util.List;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.google.api.services.sheets.v4.Sheets;
import com.google.api.services.sheets.v4.model.ValueRange;

import framework.input.Configuration;
import framework.reporter.ScreenshotType;
import pages.SubModule;
import pages.login.home.specificApp.SpecificApp;
import suites.appsuites.utils.GSheetOperation;
import suites.basesuites.RocketBaseSuite;

/**
 * Project specific base suite to be extended by every suite
 */
public class CreateAppSuite extends RocketBaseSuite implements SubModule {

	@Test(priority = 0, enabled = true, dataProvider = "customInput", description = "(Rocket Process Automation) <br>"
			+ "1. Launch the rocket.new url >> Url should be launch. <br>"
			+ "2. Click on sign in button >> Sign popup should be open. <br>"
			+ "3. Enter Gmail Id and click on continue button >> Otp field should be display. <br>"
			+ "4. Enter otp and click on continue button >> Login should be successfully and home button should be display. <br>"
			+ "5. Click on new task and enter prompt which is generated by AI Tool >> Prompt should be enter <br>"
			+ "6. Click on send button >> The development of the application should begin. <br>"
			+ "7. Click on launch button >> Successfully click on launch button and URL should be display.<br>"
			+ "8. Take the Url and Prompt >> Enter both the things in google sheet. <br>"
			+ "9. Launch the new generated url >> It should be successfully launch.")
	public void generateApp(String numberOfApps, String useCase, String technology, String typeOfApplication,
			String rowNumber) {

		String url = "Not Generated";

		// generating prompt from GEMINI
		String response = geminiService.generateGeminiPrompt(numberOfApps, useCase, technology, typeOfApplication);

		// if response is not empty then move ahead
		if (!response.isBlank()) {

			// select application type from that
			if (home.selectApplicationType(useCase, typeOfApplication)) {

				url = home.enterPromptAndGenerateURL(response);

				commonFunctions.logOut();
			}
		}

		// update the google sheet
		gSheetOperation.updateCell(response, url, Integer.valueOf(rowNumber));

		if (!url.equalsIgnoreCase("Not Generated")) {

			SpecificApp specificApp = createObject(SPECIFIC_APP);
			specificApp.verifyNewApplication(url);
		}

	}

	@DataProvider(name = "customInput")
	public Object[][] customInput() {

		try {

			gSheetOperation = new GSheetOperation();

			Sheets sheetsService = gSheetOperation.getSheetService();

			String sheetName = CreateAppSuite.class.getSimpleName();
			String cellRange = Configuration.getConfigProp("range");

			String range = sheetName + "!" + cellRange;

			log.info("Reading data from range: " + range);

			ValueRange response = sheetsService.spreadsheets().values().get(spreadSheetId, range).execute();

			List<List<Object>> values = response.getValues();

			if (values == null || values.isEmpty()) {

				log.error("No data found in Google Sheet.");

				return new Object[0][0];
			}

			int rowCount = values.size();
			int columnCount = values.get(0).size();

			data = new Object[rowCount][columnCount + 1];

			for (int i = 0; i < rowCount; i++) {

				List<Object> row = values.get(i);

				for (int j = 0; j < columnCount; j++) {

					if (j < row.size()) {

						data[i][j] = String.valueOf(row.get(j));

					} else {

						data[i][j] = "";
					}
				}

				// Add Google Sheet row number
				data[i][columnCount] = String.valueOf(i + 2);
			}

			log.info("Successfully fetched data from Google Sheet.");

		} catch (Exception e) {

			log.error("Error while reading Google Sheet data.", e);
			RESULT.FAIL("Failed to get Input data from the google sheet", false, ScreenshotType.browser);
		}

		return data;
	}
}
